### PR TITLE
Allows users to pass a custom DateTimeFormatter for the ZonedDateTime…

### PR DESCRIPTION
**Pull request by tinnou**
…Serializer

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Sounds reasonable, would be happy to merge.

Before merging the contribution, the one thing we need is a filled Contributor License Agreement (CLA), from https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf
so if it would be possible to print it, fill & sign, scan and email to `info` at fasterxml dot com, that'd be great.

Looking forward to merging this fix.

**Comment by tinnou** [comment]
Cool. Sent.

**Comment by cowtowncoder** [comment]
I will actually merge this to be included in 2.6.3 just because I haven't upgraded `master` yet -- so it will be included before 2.7. Just as an FYI; officially API shouldn't change in patch versions, but this is safe enough so as not to cause issues.

**Comment by cbornet** [comment]
Would be great to also be able to do that for OffsetDateTime !

**Comment by cowtowncoder** [comment]
PRs welcome!

**Comment by cbornet** [comment]
Yes. I'll see if I have time.
It should also be possible to easily format Instant. Then there could be a method in JavaTimeModule to set the format and timezone of all Instant based types at once.

**Comment by cowtowncoder** [comment]
@cbornet Actually there already is general-purpose support, as of 2.8:

    JsonFormat.Value format = ....;
    mapper.configOverride(Instance.class).setFormat(format);

as long as `Instance` (de)serializer accepts `@JsonFormat` information via `createContextual()`.

**Comment by cbornet** [comment]
Yes but you need to do this for Instant, ZonedDateTime, OffsetDateTime. It would be useful to have something like ```setInstantBasedTypeFormatter(DateTimeFormatter format)```. I don't think it can be done on the mapper since it belongs to the core so I'm wondering if it couldn't be done on the JavaTimeModule.

**Comment by cowtowncoder** [comment]
@cbornet It is a general facility to use and superior in that sense. But I could see benefit of having a helper method in `JavaTimeModule` that could act as shortcut like you suggest; method to call before registering.

**Pull request merged**
